name: VillagerInfo
author: IllogicalSong (Special thanks to Peashooter101)
description: Easy access to information from villager's brains generally only accessable through the /data command.
version: '${project.version}'
main: adhdmc.villagerinfo.VillagerInfo
api-version: 1.18
commands:
  vill:
    description: vill
permissions:
  villagerinfo.reload:
    description: reload plugin config
  villagerinfo.use:
    description: get the villager info from shift-right-clicking on a villager
  villagerinfo.toggle:
    description: allows toggling on/off